# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/XuanDuc/python-app/ui/item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(370, 122)
        self.lb = QtWidgets.QLabel(parent=Form)
        self.lb.setGeometry(QtCore.QRect(0, 0, 371, 121))
        self.lb.setStyleSheet("background:rgb(165, 185, 218);\n"
"border-radius:10px")
        self.lb.setText("")
        self.lb.setObjectName("lb")
        self.lb_img = QtWidgets.QLabel(parent=Form)
        self.lb_img.setGeometry(QtCore.QRect(10, 10, 100, 100))
        self.lb_img.setText("")
        self.lb_img.setScaledContents(True)
        self.lb_img.setObjectName("lb_img")
        self.rating = QtWidgets.QWidget(parent=Form)
        self.rating.setGeometry(QtCore.QRect(180, 50, 171, 51))
        self.rating.setObjectName("rating")
        self.gridLayout = QtWidgets.QGridLayout(self.rating)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lb_name = QtWidgets.QLabel(parent=Form)
        self.lb_name.setGeometry(QtCore.QRect(187, 15, 161, 31))
        self.lb_name.setObjectName("lb_name")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_name.setText(_translate("Form", "TextLabel"))
