# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/XuanDuc/python-app/ui/item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setMinimumSize(QtCore.QSize(320, 80))
        Form.setMaximumSize(QtCore.QSize(320, 90))
        Form.setStyleSheet("background:transparent; border-radius:12px;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lb_img = QtWidgets.QLabel(parent=Form)
        self.lb_img.setMinimumSize(QtCore.QSize(56, 56))
        self.lb_img.setMaximumSize(QtCore.QSize(56, 56))
        self.lb_img.setScaledContents(True)
        self.lb_img.setObjectName("lb_img")
        self.horizontalLayout.addWidget(self.lb_img)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_name = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.lb_name.setFont(font)
        self.lb_name.setStyleSheet("color:#222; font-weight:bold;")
        self.lb_name.setWordWrap(True)
        self.lb_name.setObjectName("lb_name")
        self.verticalLayout.addWidget(self.lb_name)
        self.infoLayout = QtWidgets.QHBoxLayout()
        self.infoLayout.setSpacing(4)
        self.infoLayout.setObjectName("infoLayout")
        self.lb_healthScore = QtWidgets.QLabel(parent=Form)
        self.lb_healthScore.setStyleSheet("color:green; font-weight:bold; margin:0; padding:0;")
        self.lb_healthScore.setObjectName("lb_healthScore")
        self.infoLayout.addWidget(self.lb_healthScore)
        self.lb_pricePerServing = QtWidgets.QLabel(parent=Form)
        self.lb_pricePerServing.setStyleSheet("color:orange; font-weight:bold; margin:0; padding:0;")
        self.lb_pricePerServing.setObjectName("lb_pricePerServing")
        self.infoLayout.addWidget(self.lb_pricePerServing)
        self.verticalLayout.addLayout(self.infoLayout)
        self.lb_tags = QtWidgets.QLabel(parent=Form)
        self.lb_tags.setStyleSheet("color:#0077b6; font-weight:bold; margin:0; padding:0; background:transparent; border:none;")
        self.lb_tags.setWordWrap(True)
        self.lb_tags.setObjectName("lb_tags")
        self.verticalLayout.addWidget(self.lb_tags)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass
