# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/XuanDuc/python-app/ui/loggin.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(718, 442)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_email.setGeometry(QtCore.QRect(70, 160, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.txt_email.setFont(font)
        self.txt_email.setStyleSheet("border: 1px solid #cccccc; /* Light gray border */\n"
"border-radius: 20px; /* Rounded corners */\n"
"background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"padding: 15px; /* Padding to create space around the text */\n"
"")
        self.txt_email.setText("")
        self.txt_email.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.txt_email.setObjectName("txt_email")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 130, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 310, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background: none;\n"
"border: none;\n"
"color:rgb(33, 33, 33);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.txt_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_password.setGeometry(QtCore.QRect(70, 220, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.txt_password.setFont(font)
        self.txt_password.setStyleSheet("border: 1px solid #cccccc; /* Light gray border */\n"
"    border-radius: 20px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */\n"
"color: rgb(0, 0, 0);")
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 80, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(22)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 0, 351, 451))
        self.label_5.setMaximumSize(QtCore.QSize(1080, 700))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/XuanDuc/python-app/ui/../img/49.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.btn_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(70, 280, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(16)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("color:rgb(255, 255, 255);\n"
"background: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 #87CEFA, stop:1 #4682B4);\n"
"border-radius:10px;\n"
"")
        self.btn_login.setObjectName("btn_login")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(610, 20, 81, 31))
        self.pushButton.setStyleSheet("border-radius:10px;\n"
"border: 2px solid white;\n"
"color:rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 20, 81, 31))
        self.pushButton_3.setStyleSheet("border-radius:5px;\n"
"color:rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.btn_register = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(540, 20, 81, 31))
        self.btn_register.setStyleSheet("border-radius:5px;\n"
"color:rgb(255, 255, 255)")
        self.btn_register.setObjectName("btn_register")
        self.btn_eye_p = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_eye_p.setGeometry(QtCore.QRect(250, 230, 31, 31))
        self.btn_eye_p.setStyleSheet("background: none;\n"
"border: none;")
        self.btn_eye_p.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/XuanDuc/python-app/ui/../img/eye-slash-solid.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye_p.setIcon(icon)
        self.btn_eye_p.setIconSize(QtCore.QSize(32, 32))
        self.btn_eye_p.setObjectName("btn_eye_p")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(80, 110, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(14)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -30, 381, 471))
        self.label.setStyleSheet("background:rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.label_5.raise_()
        self.txt_email.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton_2.raise_()
        self.txt_password.raise_()
        self.label_2.raise_()
        self.btn_login.raise_()
        self.pushButton.raise_()
        self.pushButton_3.raise_()
        self.btn_register.raise_()
        self.btn_eye_p.raise_()
        self.label_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.pushButton_2.setText(_translate("MainWindow", "Forgot password?"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_2.setText(_translate("MainWindow", "Login"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.pushButton.setText(_translate("MainWindow", "Login"))
        self.pushButton_3.setText(_translate("MainWindow", "Home"))
        self.btn_register.setText(_translate("MainWindow", "Sign up"))
        self.label_6.setText(_translate("MainWindow", "Have an Anccount ?"))
