# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/XuanDuc/python-app/ui/nguyen_lieu.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(90, 100)
        Form.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lb_img = QtWidgets.QLabel(parent=Form)
        self.lb_img.setGeometry(QtCore.QRect(8, 5, 71, 51))
        self.lb_img.setText("")
        self.lb_img.setObjectName("lb_img")
        self.lb_name = QtWidgets.QLabel(parent=Form)
        self.lb_name.setGeometry(QtCore.QRect(10, 60, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.lb_name.setFont(font)
        self.lb_name.setStyleSheet("color:white;")
        self.lb_name.setText("")
        self.lb_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lb_name.setObjectName("lb_name")
        self.lb_description = QtWidgets.QLabel(parent=Form)
        self.lb_description.setGeometry(QtCore.QRect(10, 80, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.lb_description.setFont(font)
        self.lb_description.setStyleSheet("color:white;")
        self.lb_description.setText("")
        self.lb_description.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.lb_description.setObjectName("lb_description")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
