# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/XuanDuc/python-app/ui/Sign_Up.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 441)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 130, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border: 1px solid #cccccc; /* Light gray border */\n"
"    border-radius: 20px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 30, 241, 321))
        self.label.setStyleSheet("border: 1px solid #cccccc; /* Light gray border */\n"
"    border-radius: 35px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 20, 81, 31))
        self.pushButton_4.setStyleSheet("border-radius:5px;\n"
"color:rgb(255, 255, 255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 20, 81, 31))
        self.pushButton_3.setStyleSheet("border-radius:5px;\n"
"\n"
"color:rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(240, 70, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: 1px solid #cccccc; /* Light gray border */\n"
"    border-radius: 20px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(550, 20, 71, 31))
        self.pushButton_5.setStyleSheet("border-radius:5px;\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid white;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 20, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(22)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 0, 711, 401))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/XuanDuc/python-app/ui/../img/hinh-nen-4k-windows-10_100821069.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(240, 190, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border: 1px solid #cccccc; /* Light gray border */\n"
"    border-radius: 20px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(260, 290, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color:rgb(255, 255, 255);\n"
"background: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 #87CEFA, stop:1 #4682B4);\n"
"border-radius:10px;\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 240, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border: none;\n"
"background: none;\n"
"color:rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.label_5.raise_()
        self.label.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_4.raise_()
        self.pushButton_3.raise_()
        self.lineEdit.raise_()
        self.pushButton_5.raise_()
        self.label_2.raise_()
        self.lineEdit_3.raise_()
        self.pushButton_6.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_2.setText(_translate("MainWindow", "password"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Name - Class"))
        self.pushButton_4.setText(_translate("MainWindow", "Home"))
        self.pushButton_3.setText(_translate("MainWindow", "Login"))
        self.lineEdit.setText(_translate("MainWindow", "Name"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Name school"))
        self.pushButton_5.setText(_translate("MainWindow", "Sign up"))
        self.label_2.setText(_translate("MainWindow", "Sign Up"))
        self.lineEdit_3.setText(_translate("MainWindow", "anccont bank"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Email"))
        self.pushButton_6.setText(_translate("MainWindow", "Sign Up"))
        self.pushButton.setText(_translate("MainWindow", "How to make account"))
