# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA08/XuanDuc/python-app/ui/Sign_Up.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 441)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_password.setGeometry(QtCore.QRect(80, 220, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.txt_password.setFont(font)
        self.txt_password.setStyleSheet("border: 1px solid #cccccc; /* Light gray border */\n"
"    border-radius: 20px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */")
        self.txt_password.setText("")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.txt_password.setObjectName("txt_password")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 20, 81, 31))
        self.pushButton_4.setStyleSheet("border-radius:5px;\n"
"color:rgb(255, 255, 255)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.btn_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(610, 20, 81, 31))
        self.btn_login.setStyleSheet("border-radius:5px;\n"
"\n"
"color:rgb(255, 255, 255)")
        self.btn_login.setObjectName("btn_login")
        self.txt_name = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_name.setGeometry(QtCore.QRect(80, 100, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.txt_name.setFont(font)
        self.txt_name.setStyleSheet("border: 1px solid #cccccc; /* Light gray border */\n"
"    border-radius: 20px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */")
        self.txt_name.setText("")
        self.txt_name.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.txt_name.setObjectName("txt_name")
        self.btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(550, 20, 71, 31))
        self.btn.setStyleSheet("border-radius:10px;\n"
"color:rgb(255, 255, 255);\n"
"border: 2px solid white;")
        self.btn.setObjectName("btn")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 40, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(22)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_email.setGeometry(QtCore.QRect(80, 160, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.txt_email.setFont(font)
        self.txt_email.setStyleSheet("border: 1px solid #cccccc; /* Light gray border */\n"
"    border-radius: 20px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */")
        self.txt_email.setText("")
        self.txt_email.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.txt_email.setObjectName("txt_email")
        self.btn_register = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(80, 340, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        self.btn_register.setFont(font)
        self.btn_register.setStyleSheet("color:rgb(255, 255, 255);\n"
"background: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 #87CEFA, stop:1 #4682B4);\n"
"border-radius:10px;\n"
"")
        self.btn_register.setObjectName("btn_register")
        self.btn_Make_acc = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_Make_acc.setGeometry(QtCore.QRect(150, 370, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setBold(True)
        self.btn_Make_acc.setFont(font)
        self.btn_Make_acc.setStyleSheet("border: none;\n"
"background: none;\n"
"color:rgb(0, 0, 0)")
        self.btn_Make_acc.setObjectName("btn_Make_acc")
        self.btn_eye_p = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_eye_p.setGeometry(QtCore.QRect(420, 220, 31, 31))
        self.btn_eye_p.setStyleSheet("background: none;\n"
"border: none;")
        self.btn_eye_p.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/XuanDuc/python-app/ui/../img/eye-slash-solid.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye_p.setIcon(icon)
        self.btn_eye_p.setIconSize(QtCore.QSize(32, 32))
        self.btn_eye_p.setObjectName("btn_eye_p")
        self.txt_confirm_pwd = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_confirm_pwd.setGeometry(QtCore.QRect(80, 280, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.txt_confirm_pwd.setFont(font)
        self.txt_confirm_pwd.setStyleSheet("border: 1px solid #cccccc; /* Light gray border */\n"
"    border-radius: 20px; /* Rounded corners */\n"
"    background-color: rgba(255, 255, 255, 0.1); /* Transparent-like background */\n"
"    padding: 15px; /* Padding to create space around the text */")
        self.txt_confirm_pwd.setText("")
        self.txt_confirm_pwd.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.txt_confirm_pwd.setObjectName("txt_confirm_pwd")
        self.btn_eye_cp = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_eye_cp.setGeometry(QtCore.QRect(420, 270, 31, 31))
        self.btn_eye_cp.setStyleSheet("background: none;\n"
"border: none;")
        self.btn_eye_cp.setText("")
        self.btn_eye_cp.setIcon(icon)
        self.btn_eye_cp.setIconSize(QtCore.QSize(32, 32))
        self.btn_eye_cp.setObjectName("btn_eye_cp")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(380, 0, 351, 451))
        self.label_5.setMaximumSize(QtCore.QSize(1080, 700))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA08/XuanDuc/python-app/ui/../img/49.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 381, 471))
        self.label.setStyleSheet("background:rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.label_5.raise_()
        self.txt_password.raise_()
        self.pushButton_4.raise_()
        self.btn_login.raise_()
        self.txt_name.raise_()
        self.btn.raise_()
        self.label_2.raise_()
        self.txt_email.raise_()
        self.btn_register.raise_()
        self.btn_Make_acc.raise_()
        self.btn_eye_p.raise_()
        self.txt_confirm_pwd.raise_()
        self.btn_eye_cp.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", "password"))
        self.pushButton_4.setText(_translate("MainWindow", "Home"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.txt_name.setPlaceholderText(_translate("MainWindow", "Name "))
        self.btn.setText(_translate("MainWindow", "Sign up"))
        self.label_2.setText(_translate("MainWindow", "Sign Up"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.btn_register.setText(_translate("MainWindow", "Sign Up"))
        self.btn_Make_acc.setText(_translate("MainWindow", "How to make account"))
        self.txt_confirm_pwd.setPlaceholderText(_translate("MainWindow", "confirm_password"))
